trigger:
- main

pool:
  name: 'K8S-Agents'

variables:
  name: 'Mr. Clean'

jobs:
- job: HelloUser
  displayName: 'Say hello to the user'
  steps:
  - bash: |
      echo 'Hello there, $(name)'
    displayName: 'Say Hello'
  
  - bash: |
      curl 'https://www.google.com/'
    displayName: 'Curl that google'